package Engine;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;

class Window extends JFrame{
    public final int w, h;
    public final Insets bounds;
    private static Window instance;
    protected KeyMap km;

    private Window(int w, int h, boolean fullscreen){
        this.w = w;
        this.h = h;
        this.setSize(w, h);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        if(fullscreen) {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.setUndecorated(true);
        }
        bounds = this.getInsets();
        this.setVisible(true);
    }

    // Key input listener, got this from Engine, generated by KeyMapping
    void addKeyMapping(KeyMap map){
        this.addKeyListener(map);
        this.km = map;
    }

    public static Window get(int w, int h, boolean fullscreen){
        if(instance==null){
            instance = new Window(w, h, fullscreen);
        }
        return instance;
    }

    @Override
    public String toString(){
        return String.format("Window[%d,%d]", w, h);
    }

    public void close(){
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
}
